// Generated by https://quicktype.io

export interface Message {
    idAudioMessage: number;
    name:           string;
    description:    string;
    message:        null;
    creationTime:   string;
    updateTime:     string;
}
